const products = [
  {
    id: 1,
    name: "AeroTune Headphones",
    brand: "North Audio",
    category: "Tech",
    price: 129,
    originalPrice: 159,
    rating: 4.8,
    reviews: 1260,
    stock: 14,
    sold: 890,
    badge: "Best seller",
    description: "Noise-softening over-ear headphones with 38 hour battery life.",
    tags: ["audio", "wireless", "travel"],
    imageUrl:
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80",
    imageAlt: "Silver and black over-ear headphones",
    accent: "#2563eb",
    deliveryEta: "2 day delivery",
  },
  {
    id: 2,
    name: "Lumbar Cloud Chair",
    brand: "Hearth & Form",
    category: "Home",
    price: 214,
    originalPrice: 260,
    rating: 4.7,
    reviews: 834,
    stock: 9,
    sold: 640,
    badge: "Ergonomic",
    description: "Soft-touch lounge chair with a curved supportive back.",
    tags: ["furniture", "comfort", "living room"],
    imageUrl:
      "https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?auto=format&fit=crop&w=900&q=80",
    imageAlt: "Modern upholstered lounge chair",
    accent: "#0f766e",
    deliveryEta: "4 day delivery",
  },
  {
    id: 3,
    name: "Urban Daypack",
    brand: "Forge Street",
    category: "Style",
    price: 86,
    originalPrice: 112,
    rating: 4.6,
    reviews: 956,
    stock: 18,
    sold: 780,
    badge: "Everyday",
    description: "Water-resistant commuter backpack with padded laptop storage.",
    tags: ["bag", "commute", "travel"],
    imageUrl:
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80",
    imageAlt: "Black commuter backpack",
    accent: "#7c3aed",
    deliveryEta: "2 day delivery",
  },
  {
    id: 4,
    name: "Ember Pour Kettle",
    brand: "Copper & Co.",
    category: "Kitchen",
    price: 74,
    originalPrice: 92,
    rating: 4.5,
    reviews: 612,
    stock: 22,
    sold: 510,
    badge: "Chef pick",
    description: "Gooseneck kettle with quick heat control for coffee and tea.",
    tags: ["coffee", "tea", "kettle"],
    imageUrl:
      "https://images.unsplash.com/photo-1516714435131-44d6b64dc6a2?auto=format&fit=crop&w=900&q=80",
    imageAlt: "Metal pour-over kettle on a counter",
    accent: "#dc2626",
    deliveryEta: "3 day delivery",
  },
  {
    id: 5,
    name: "PixelDock Station",
    brand: "Circuit Loft",
    category: "Tech",
    price: 149,
    originalPrice: 179,
    rating: 4.4,
    reviews: 488,
    stock: 11,
    sold: 430,
    badge: "New",
    description: "Compact USB-C dock with display, power, and card ports.",
    tags: ["usb-c", "desktop", "charging"],
    imageUrl:
      "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=900&q=80",
    imageAlt: "Compact computer docking station",
    accent: "#0891b2",
    deliveryEta: "2 day delivery",
  },
  {
    id: 6,
    name: "TerraGlow Lamp",
    brand: "Nest Theory",
    category: "Home",
    price: 68,
    rating: 4.3,
    reviews: 344,
    stock: 16,
    sold: 390,
    badge: "Warm glow",
    description: "Ceramic table lamp with dimmable amber light.",
    tags: ["lighting", "decor", "ceramic"],
    imageUrl:
      "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80",
    imageAlt: "Minimal table lamp glowing on a side table",
    accent: "#ca8a04",
    deliveryEta: "3 day delivery",
  },
  {
    id: 7,
    name: "TrailSip Bottle",
    brand: "Range Supply",
    category: "Outdoor",
    price: 38,
    originalPrice: 46,
    rating: 4.9,
    reviews: 1420,
    stock: 36,
    sold: 720,
    badge: "Top rated",
    description: "Insulated stainless bottle that keeps drinks cold for 24 hours.",
    tags: ["hydration", "camping", "fitness"],
    imageUrl:
      "https://images.unsplash.com/photo-1523362628745-0c100150b504?auto=format&fit=crop&w=900&q=80",
    imageAlt: "Reusable water bottle outdoors",
    accent: "#16a34a",
    deliveryEta: "2 day delivery",
  },
  {
    id: 8,
    name: "CoreBalance Mat",
    brand: "Vita Studio",
    category: "Wellness",
    price: 58,
    originalPrice: 72,
    rating: 4.6,
    reviews: 528,
    stock: 20,
    sold: 310,
    badge: "Studio grade",
    description: "Non-slip exercise mat with extra cushioning for daily practice.",
    tags: ["yoga", "fitness", "recovery"],
    imageUrl:
      "https://images.unsplash.com/photo-1592432678016-e910b452f9a2?auto=format&fit=crop&w=900&q=80",
    imageAlt: "Rolled yoga mat on a studio floor",
    accent: "#db2777",
    deliveryEta: "2 day delivery",
  },
  {
    id: 9,
    name: "FocusFlow Desk Tray",
    brand: "Paperlane",
    category: "Office",
    price: 44,
    rating: 4.2,
    reviews: 210,
    stock: 27,
    sold: 245,
    badge: "Organized",
    description: "Stackable desk tray set for papers, notes, and accessories.",
    tags: ["desk", "organization", "work"],
    imageUrl:
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80",
    imageAlt: "Organized desk with work accessories",
    accent: "#475569",
    deliveryEta: "3 day delivery",
  },
  {
    id: 10,
    name: "Atlas Knit Hoodie",
    brand: "Common Thread",
    category: "Style",
    price: 96,
    originalPrice: 118,
    rating: 4.7,
    reviews: 704,
    stock: 15,
    sold: 560,
    badge: "Soft knit",
    description: "Midweight cotton-blend hoodie with a relaxed modern fit.",
    tags: ["apparel", "hoodie", "casual"],
    imageUrl:
      "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=900&q=80",
    imageAlt: "Folded casual hoodie",
    accent: "#111827",
    deliveryEta: "2 day delivery",
  },
  {
    id: 11,
    name: "LinenWeave Throw",
    brand: "Quiet House",
    category: "Home",
    price: 82,
    originalPrice: 98,
    rating: 4.5,
    reviews: 398,
    stock: 13,
    sold: 300,
    badge: "Cozy",
    description: "Textured linen-cotton throw blanket for sofa or bed layers.",
    tags: ["blanket", "decor", "linen"],
    imageUrl:
      "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=900&q=80",
    imageAlt: "Soft throw blanket on a sofa",
    accent: "#a16207",
    deliveryEta: "3 day delivery",
  },
  {
    id: 12,
    name: "SolarBeam Lantern",
    brand: "Campwell",
    category: "Outdoor",
    price: 64,
    originalPrice: 79,
    rating: 4.4,
    reviews: 286,
    stock: 19,
    sold: 275,
    badge: "Solar",
    description: "Rechargeable solar lantern with adjustable campsite brightness.",
    tags: ["camping", "light", "solar"],
    imageUrl:
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80",
    imageAlt: "Lantern lighting an outdoor campsite",
    accent: "#ea580c",
    deliveryEta: "4 day delivery",
  },
];

module.exports = { products };
